import {PropsWithChildren} from "react";
import Head from "next/head";
import {createTheme} from "@mui/material/styles";
import {ThemeProvider} from "@mui/material";


const Layout = ({children}: PropsWithChildren<{}>) => {
    const darkTheme = createTheme({
        components: {
        },
        palette: {
            mode: 'dark',
            primary: {
                light: '#757ce8',
                main: '#b2b0b0',
                dark: '#eeeeee',
                contrastText: '#ffffff',
            },
            secondary: {
                light: '#ff7961',
                main: '#f44336',
                dark: '#ba000d',
                contrastText: '#a6a6a6',
            },
        },
    });

    return (
        <ThemeProvider theme={darkTheme}>
            <Head>
                <title>Next.js title</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main >{
                children
            }
                <div>
                </div>
            </main>
        </ThemeProvider>
    )


};

export default Layout;